apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigservdep
spec:
  selector:
    matchLabels:
      app: apigserv
  replicas: 1
  template:
    metadata:
      labels:
        app: apigserv
    spec:
      containers:
        - name: apigserv
          image: apigserv:vf
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: apigserv
spec:
  selector:
    app: apigserv
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.