apiVersion: apps/v1
kind: Deployment
metadata:
  name: addrservdep
spec:
  selector:
    matchLabels:
      app: addrserv
  replicas: 1
  template:
    metadata:
      labels:
        app: addrserv
    spec:
      containers:
        - name: addrserv
          image: addrserv:vf
          ports:
            - containerPort: 8087
          imagePullPolicy: Never
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: addrserv
spec:
  selector:
    app: addrserv
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8087 # The port exposed by the service
  type: ClusterIP # type of the service.