apiVersion: apps/v1
kind: Deployment
metadata:
  name: discservdep
spec:
  selector:
    matchLabels:
      app: discserv
  replicas: 1
  template:
    metadata:
      labels:
        app: discserv
    spec:
      containers:
        - name: discserv
          image: discserv:vf
          ports:
            - containerPort: 8752
          imagePullPolicy: Never
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: discserv
spec:
  selector:
    app: discserv
  ports:
    - protocol: "TCP"
      port: 8752 # The port that the service is running on in the cluster
      targetPort: 8752 # The port exposed by the service
  type: ClusterIP # type of the service.